export const GENRES = [
  { value: "all", label: "All Categories" },
  { value: "games", label: "Games" },
  { value: "business", label: "Business" },
  { value: "weather", label: "Weather" },
  { value: "utilities", label: "Utilities" },
  { value: "travel", label: "Travel" },
  { value: "sports", label: "Sports" },
  { value: "social", label: "Social Networking" },
  { value: "reference", label: "Reference" },
  { value: "productivity", label: "Productivity" },
  { value: "photo-video", label: "Photo & Video" },
  { value: "news", label: "News" },
  { value: "navigation", label: "Navigation" },
  { value: "music", label: "Music" },
  { value: "lifestyle", label: "Lifestyle" },
  { value: "health-fitness", label: "Health & Fitness" },
  { value: "finance", label: "Finance" },
  { value: "entertainment", label: "Entertainment" },
  { value: "education", label: "Education" },
  { value: "books", label: "Books" },
  { value: "medical", label: "Medical" },
  { value: "magazines", label: "Magazines & Newspapers" },
  { value: "catalogs", label: "Catalogs" },
  { value: "food-drink", label: "Food & Drink" },
  { value: "shopping", label: "Shopping" },
  { value: "developer-tools", label: "Developer Tools" },
  { value: "graphics-design", label: "Graphics & Design" },
];

export const GAME_SUBGENRES = [
  { value: "games-action", label: "Games > Action" },
  { value: "games-adventure", label: "Games > Adventure" },
  { value: "games-arcade", label: "Games > Arcade" },
  { value: "games-board", label: "Games > Board" },
  { value: "games-card", label: "Games > Card" },
  { value: "games-casino", label: "Games > Casino" },
  { value: "games-dice", label: "Games > Dice" },
  { value: "games-educational", label: "Games > Educational" },
  { value: "games-family", label: "Games > Family" },
  { value: "games-kids", label: "Games > Kids" },
  { value: "games-music", label: "Games > Music" },
  { value: "games-puzzle", label: "Games > Puzzle" },
  { value: "games-racing", label: "Games > Racing" },
  { value: "games-role", label: "Games > Role Playing" },
  { value: "games-simulation", label: "Games > Simulation" },
  { value: "games-sports", label: "Games > Sports" },
  { value: "games-strategy", label: "Games > Strategy" },
  { value: "games-trivia", label: "Games > Trivia" },
  { value: "games-word", label: "Games > Word" },
];

export const COUNTRIES = [
  { code: "us", name: "United States" },
  { code: "vn", name: "Vietnam" },
  { code: "jp", name: "Japan" },
  { code: "kr", name: "South Korea" },
  { code: "gb", name: "United Kingdom" },
  { code: "de", name: "Germany" },
  { code: "fr", name: "France" },
  { code: "ca", name: "Canada" },
  { code: "au", name: "Australia" },
  { code: "cn", name: "China" },
  { code: "tw", name: "Taiwan" },
  { code: "hk", name: "Hong Kong" },
  { code: "sg", name: "Singapore" },
  { code: "my", name: "Malaysia" },
  { code: "th", name: "Thailand" },
  { code: "ph", name: "Philippines" },
  { code: "id", name: "Indonesia" },
  { code: "in", name: "India" },
  { code: "br", name: "Brazil" },
  { code: "mx", name: "Mexico" },
  { code: "it", name: "Italy" },
  { code: "es", name: "Spain" },
  { code: "ru", name: "Russia" },
  { code: "sa", name: "Saudi Arabia" },
  { code: "ae", name: "United Arab Emirates" },
  { code: "nl", name: "Netherlands" },
  { code: "se", name: "Sweden" },
  { code: "no", name: "Norway" },
  { code: "dk", name: "Denmark" },
  { code: "fi", name: "Finland" },
  { code: "ch", name: "Switzerland" },
  { code: "at", name: "Austria" },
  { code: "be", name: "Belgium" },
  { code: "pl", name: "Poland" },
  { code: "tr", name: "Turkey" },
  { code: "eg", name: "Egypt" },
  { code: "za", name: "South Africa" },
  { code: "nz", name: "New Zealand" },
  { code: "ar", name: "Argentina" },
  { code: "cl", name: "Chile" },
  { code: "co", name: "Colombia" },
  { code: "pt", name: "Portugal" },
  { code: "ie", name: "Ireland" },
  { code: "gr", name: "Greece" },
  { code: "cz", name: "Czechia" },
  { code: "hu", name: "Hungary" },
  { code: "ro", name: "Romania" },
  { code: "ua", name: "Ukraine" },
];

export const CHARTS = [
  { value: "top-free", label: "Top Free" },
  { value: "top-paid", label: "Top Paid" },
  { value: "top-grossing", label: "Top Grossing" },
];
